In [1]:
#install using either conda install numpy or pip install numpy
import numpy as np


In [2]:
#numpy attributes
dir(np)


['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

# Arrays

## Creation

In [4]:
arr1 = np.array([2,4,6,8,9])
arr1

array([2, 4, 6, 8, 9])

In [5]:
list1 = ['FirstName', 'LastName', 'Age' , 'RegNumber','Course','Year'
        ]
list2 = [2004,1968,1994,2001,1970,1996]
arr2 = np.array([list1,list2])
arr2

array([['FirstName', 'LastName', 'Age', 'RegNumber', 'Course', 'Year'],
       ['2004', '1968', '1994', '2001', '1970', '1996']], dtype='<U11')

In [99]:
arr2.shape

(2, 6)

In [100]:
arr2.ndim

2

In [6]:
arr_zeros = np.zeros(7)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr_ones = np.ones(3)
arr_ones


array([1., 1., 1.])

In [10]:
#np.empty creates empty array but stores random elements before you can decide what to do with it
arr_empty = np.empty(6)
arr_empty


array([1.14073631e+243, 5.02726990e+180, 1.06400250e+248, 2.08507603e-115,
       4.24432921e+175, 3.99281087e+252])

In [9]:
arr_range = np.arange(10,91,3)
arr_range

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [18]:
#dtype
#default data type in arrays is float eg 0. , 1. etc. 
#we use dtype keyword to explicityly specify datatype
Ones = np.ones(15 , dtype = np.int64)
zeros = np.zeros(12, dtype = np.int32)
emptyArray = np.empty(10, dtype = np.str_)


In [14]:
Ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [19]:
emptyArray

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [15]:
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Sorting and Joining

In [20]:
x1 = np.empty(10, dtype = np.int8)
x2 = np.empty(10, dtype = np.int16)


In [21]:
x1

array([   0,  -80,  121,   24, -110,    1,    0,    0,    0,    0],
      dtype=int8)

In [22]:
x2

array([2, 0, 4, 0, 6, 0, 8, 0, 9, 0], dtype=int16)

In [23]:
#np.sort gives a copy of sorted array and doesnt replace it
np.sort(x1)

array([-110,  -80,    0,    0,    0,    0,    0,    1,   24,  121],
      dtype=int8)

In [26]:
x1_sorted = np.sort(x1)
x1_sorted

array([-110,  -80,    0,    0,    0,    0,    0,    1,   24,  121],
      dtype=int8)

In [27]:
x1


array([   0,  -80,  121,   24, -110,    1,    0,    0,    0,    0],
      dtype=int8)

In [30]:
np.concatenate((x1,x2))

array([   0,  -80,  121,   24, -110,    1,    0,    0,    0,    0,    2,
          0,    4,    0,    6,    0,    8,    0,    9,    0], dtype=int16)

In [32]:
joinedArray = np.concatenate((x1,x2))
joinedArray

array([   0,  -80,  121,   24, -110,    1,    0,    0,    0,    0,    2,
          0,    4,    0,    6,    0,    8,    0,    9,    0], dtype=int16)

In [33]:
np.sort(joinedArray)

array([-110,  -80,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    1,    2,    4,    6,    8,    9,   24,  121], dtype=int16)

## Shape and Sizes

In [34]:
array_example = np.array([[[0, 1, 2, 3],

                           [4, 5, 6, 7]],


                          [[0, 1, 2, 3],

                           [4, 5, 6, 7]],


                          [[0 ,1 ,2, 3],

                           [4, 5, 6, 7]]])

In [35]:
#number of dimensions
array_example.ndim

3

In [36]:
#total number of elements
array_example.size

24

In [37]:
#shape of array
array_example.shape


(3, 2, 4)

### Reshaping
Use .reshape() method. 

In [57]:
array_reshaping = np.arange (0,150,5)
array_reshaping

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [58]:
array_reshaping.size

30

In [59]:
array_reshaping.ndim

1

In [60]:
array_reshaping.shape

(30,)

In [62]:

x_reshaped = array_reshaping.reshape(6,5)
x_reshaped

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145]])

In [97]:
y_reshaped = array_reshaping.reshape(2,3,5)
y_reshaped

array([[[  0,   5,  10,  15,  20],
        [ 25,  30,  35,  40,  45],
        [ 50,  55,  60,  65,  70]],

       [[ 75,  80,  85,  90,  95],
        [100, 105, 110, 115, 120],
        [125, 130, 135, 140, 145]]])

In [95]:
y_reshaped.shape

(2, 3, 5)

In [98]:
y_reshaped.size

30

In [69]:
new_shape = np.reshape(array_reshaping, newshape=(3,10))
new_shape

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145]])

In [66]:
x_reshaped.ndim

2

In [67]:
y_reshaped.ndim

3

In [70]:
new_shape.ndim

2

In [92]:
print('x_reshaped size =',{x_reshaped.size},end=' ',
     )

x_reshaped size = {30} 

In [93]:
print(
     'x_reshaped shape= ', {x_reshaped.shape})

x_reshaped shape=  {(6, 5)}


In [101]:
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [102]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)